# SMILES Generation from InChI

The purpose of this notebook is to generate a processed version of the dataset that will have a SMILES column

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%load_ext dotenv
%dotenv

In [ ]:
import sys
import pandas as pd
import numpy as np
from pyprojroot import here
from dl_hplc_smrt.utils import inchi_to_smiles

## Path and Files Names

In [4]:
RAW_DATA_PATH = here() / "data" / "raw"
PROCESSED_DATA_PATH = here() / "data" / "processed"

In [5]:
ORIGINAL_SMRT_FILE = RAW_DATA_PATH / "SMRT_dataset.csv"
PROCESSED_SMRT_FILE = PROCESSED_DATA_PATH / "proc_SMRT_dataset.csv"

## Reading the original dataset

In [6]:
smrt_dataset_df = pd.read_csv(ORIGINAL_SMRT_FILE, sep=";")
print(smrt_dataset_df.shape)
smrt_dataset_df.head()

(80038, 3)

   pubchem     rt                                              inchi
0     5139   93.5    InChI=1S/C3H8N2S/c1-2-6-3(4)5/h2H2,1H3,(H3,4,5)
1     3505  687.8  InChI=1S/C19H25Cl2N3O3/c1-27-19(26)23-8-9-24(1...
2     2159  590.7  InChI=1S/C17H27N3O4S/c1-4-20-8-6-7-12(20)11-19...
3     1340  583.6  InChI=1S/C9H7NO2/c11-8-3-1-2-7-6(8)4-5-10-9(7)...
4     3344  579.0  InChI=1S/C15H20N2O2/c18-14-16-12-15(19-14)7-10...

Apparently there are a few repeated InChI strings:

In [7]:
smrt_dataset_df.describe(include=['category', 'object'])

/tmp/ipykernel_49004/2913326157.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  smrt_dataset_df.describe(include=['category', 'object'])

                                                    inchi
count                                               80038
unique                                              80019
top     InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-...
freq                                                    3

Let's investigate that

In [8]:
inchi_counts = smrt_dataset_df['inchi'].value_counts()
repeated_inchis = inchi_counts[inchi_counts > 1]

In [9]:
repeated_inchis = repeated_inchis.index
repeated_inchis

Index(['InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-13)21-17(20)16(11-19)12-5-3-2-4-6-12/h2-6,13-16,19H,7-11H2,1H3/t13-,14+,15-,16-/m1/s1',
       'InChI=1S/C15H20O3/c1-9-5-4-8-15(3)13(18-15)12-11(7-6-9)10(2)14(16)17-12/h5,11-13H,2,4,6-8H2,1,3H3/b9-5-/t11-,12-,13+,15+/m0/s1',
       'InChI=1S/C4H8N2O2/c5-3-1-2-6(8)4(3)7/h3,8H,1-2,5H2/t3-/m0/s1',
       'InChI=1S/C17H25NO/c19-17-9-5-4-8-16(17)18-12-10-15(11-13-18)14-6-2-1-3-7-14/h1-3,6-7,15-17,19H,4-5,8-13H2/t16-,17+/m0/s1',
       'InChI=1S/C26H28ClNO/c1-3-28(4-2)19-20-29-24-17-15-22(16-18-24)25(21-11-7-5-8-12-21)26(27)23-13-9-6-10-14-23/h5-18H,3-4,19-20H2,1-2H3/b26-25-',
       'InChI=1S/C17H21NO4/c1-18-13-7-11(8-14(18)16-15(13)22-16)21-17(20)12(9-19)10-5-3-2-4-6-10/h2-6,11-16,19H,7-9H2,1H3/t11-,12-,13+,14-,15+,16-/m1/s1',
       'InChI=1S/C13H15NO2/c15-12-7-9-4-5-10-8-13(9,16-12)11-3-1-2-6-14(10)11/h4-5,7,10-11H,1-3,6,8H2/t10-,11-,13+/m1/s1',
       'InChI=1S/C29H41F2N5O/c1-19(2)27-34-33-20(3)36(27)25-17-23-9-10-24(18-25)35(23)16-13-26(21-7-5-4-6-8-21)32-28(37)22-11-14-29(30,31)15-12-22/h4-8,19,22-26H,9-18H2,1-3H3,(H,32,37)/t23-,24+,25-,26-/m0/s1',
       'InChI=1S/C16H24O4/c1-11-5-3-2-4-6-12-9-13(17)10-14(12)15(18)7-8-16(19)20-11/h4,6-8,11-15,17-18H,2-3,5,9-10H2,1H3/b6-4+,8-7+/t11-,12+,13-,14+,15+/m0/s1',
       'InChI=1S/C13H13N3/c1-2-16-13-5-11-9-3-8(6-14-7-9)10(11)4-12(13)15-1/h1-2,4-5,8-9,14H,3,6-7H2/t8-,9+',
       'InChI=1S/C21H24N2O2/c1-3-14-10-13-11-21(20(24)25-2)18-16(8-9-23(12-13)19(14)21)15-6-4-5-7-17(15)22-18/h4-7,10,13,19,22H,3,8-9,11-12H2,1-2H3/t13-,19+,21-/m0/s1',
       'InChI=1S/C26H25NO4/c28-18-8-7-15-11-20-26(29)12-17-16-3-1-2-4-19(16)30-22(17)24-25(26,21(15)23(18)31-24)9-10-27(20)13-14-5-6-14/h1-4,7-8,14,20,24,28-29H,5-6,9-13H2/t20-,24+,25+,26-/m1/s1',
       'InChI=1S/C27H42N2O5S/c1-15-9-8-10-27(7)22(34-27)12-20(16(2)11-19-14-35-18(4)28-19)29-23(31)13-21(30)26(5,6)25(33)17(3)24(15)32/h11,14-15,17,20-22,24,30,32H,8-10,12-13H2,1-7H3,(H,29,31)/b16-11+/t15-,17+,20-,21-,22-,24-,27+/m0/s1',
       'InChI=1S/C23H27N5/c1-19-23(20(2)28(25-19)22-11-7-4-8-12-22)17-24-27-15-13-26(14-16-27)18-21-9-5-3-6-10-21/h3-12,17H,13-16,18H2,1-2H3/b24-17+',
       'InChI=1S/C26H26N2O3/c1-14(2)13-28-10-9-25-21-15-7-8-19(29)23(21)31-24(25)22-17(12-26(25,30)20(28)11-15)16-5-3-4-6-18(16)27-22/h3-8,20,24,27,29-30H,1,9-13H2,2H3/t20-,24+,25+,26-/m1/s1',
       'InChI=1S/C26H26N2O3/c29-19-8-7-15-11-20-26(30)12-17-16-3-1-2-4-18(16)27-22(17)24-25(26,21(15)23(19)31-24)9-10-28(20)13-14-5-6-14/h1-4,7-8,14,20,24,27,29-30H,5-6,9-13H2/t20-,24+,25+,26-/m1/s1',
       'InChI=1S/C21H27NO4/c23-14-5-4-13-10-16-21(25)7-6-15(24)19-20(21,17(13)18(14)26-19)8-9-22(16)11-12-2-1-3-12/h4-5,12,15-16,19,23-25H,1-3,6-11H2/t15-,16+,19-,20-,21+/m0/s1'],
      dtype='str', name='inchi')

In [10]:
smrt_dataset_repeated_df = smrt_dataset_df.loc[smrt_dataset_df["inchi"].isin(repeated_inchis), :]
smrt_dataset_repeated_df.head()

     pubchem      rt                                              inchi
11      1232   620.6  InChI=1S/C4H8N2O2/c5-3-1-2-6(8)4(3)7/h3,8H,1-2...
42      3661   638.0  InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-...
54      5662   679.1  InChI=1S/C17H25NO/c19-17-9-5-4-8-16(17)18-12-1...
176     2800  1008.2  InChI=1S/C26H28ClNO/c1-3-28(4-2)19-20-29-24-17...
615  2723877   581.3  InChI=1S/C17H21NO4/c1-18-13-7-11(8-14(18)16-15...

In [11]:
smrt_dataset_repeated_aggregated_df = smrt_dataset_repeated_df.loc[:,['inchi','rt']].groupby('inchi').agg(
    rt_min = ('rt', 'min'),
    rt_max = ('rt', 'max'),
    rt_mean = ('rt', 'mean')
    ).reset_index()

In [12]:
smrt_dataset_repeated_aggregated_df['pubchem'] = smrt_dataset_repeated_aggregated_df['inchi'].apply(lambda inchi: smrt_dataset_repeated_df.loc[smrt_dataset_repeated_df["inchi"]==inchi,"pubchem"].to_list())

In [13]:
smrt_dataset_repeated_aggregated_df.head(10)

,inchi,rt_min,rt_max,rt_mean,pubchem
0,InChI=1S/C13H13N3/c1-2-16-13-5-11-9-3-8(6-14-7...,92.3,101.1,96.700000,"[5310966, 170361]"
1,"InChI=1S/C13H15NO2/c15-12-7-9-4-5-10-8-13(9,16...",86.4,94.5,90.450000,"[267769, 6338099]"
2,InChI=1S/C15H20O3/c1-9-5-4-8-15(3)13(18-15)12-...,843.6,972.3,904.766667,"[5420804, 7251185, 927704]"
3,InChI=1S/C16H24O4/c1-11-5-3-2-4-6-12-9-13(17)1...,732.2,781.6,756.900000,"[5287620, 6436187]"
4,InChI=1S/C17H21NO4/c1-18-13-7-11(8-14(18)16-15...,581.3,619.4,600.350000,"[2723877, 3000322]"
5,InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-...,613.3,667.1,639.466667,"[3661, 64692, 174174]"
6,InChI=1S/C17H25NO/c19-17-9-5-4-8-16(17)18-12-1...,679.1,701.9,690.500000,"[5662, 16411702]"
7,InChI=1S/C21H24N2O2/c1-3-14-10-13-11-21(20(24)...,681.1,727.8,704.450000,"[5458190, 72315]"
8,InChI=1S/C21H27NO4/c23-14-5-4-13-10-16-21(25)7...,618.9,635.1,627.000000,"[11957646, 16741281]"
9,InChI=1S/C23H27N5/c1-19-23(20(2)28(25-19)22-11...,687.2,739.4,713.300000,"[6878030, 1356208]"

Most of the values for the different molecules with shared InChI are rather similar. Furthermore, visual inspection of a few of those molecules hint towrads them being different only in terms of chiral centers (sometimes they may correspond to different enantiomers, sometimes some of the centers appear to be racemic). We will not deal with stereochemistry, so we will input the mean instead and keep just one copy.

## Remove Duplicates and Input the Mean Retention Time

Remove duplicates keeping just the first instance

In [14]:
print(smrt_dataset_df.shape)
smrt_dataset_df.drop_duplicates(subset=['inchi'], inplace=True)
print(smrt_dataset_df.shape)

(80038, 3)
(80019, 3)

Input the mean for those that had duplicates

In [15]:
mask_duplicated = smrt_dataset_df["inchi"].isin(smrt_dataset_repeated_aggregated_df["inchi"])

In [16]:
smrt_dataset_df.loc[mask_duplicated, :].head(10)

      pubchem      rt                                              inchi
11       1232   620.6  InChI=1S/C4H8N2O2/c5-3-1-2-6(8)4(3)7/h3,8H,1-2...
42       3661   638.0  InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-...
54       5662   679.1  InChI=1S/C17H25NO/c19-17-9-5-4-8-16(17)18-12-1...
176      2800  1008.2  InChI=1S/C26H28ClNO/c1-3-28(4-2)19-20-29-24-17...
615   2723877   581.3  InChI=1S/C17H21NO4/c1-18-13-7-11(8-14(18)16-15...
708    267769    86.4  InChI=1S/C13H15NO2/c15-12-7-9-4-5-10-8-13(9,16...
1489  3002977   665.8  InChI=1S/C29H41F2N5O/c1-19(2)27-34-33-20(3)36(...
3896  5287620   781.6  InChI=1S/C16H24O4/c1-11-5-3-2-4-6-12-9-13(17)1...
3934  5310966   101.1  InChI=1S/C13H13N3/c1-2-16-13-5-11-9-3-8(6-14-7...
4147  5420804   972.3  InChI=1S/C15H20O3/c1-9-5-4-8-15(3)13(18-15)12-...

Let's copy the rt values to old_rt

In [17]:
smrt_dataset_df["old_rt"] = smrt_dataset_df["rt"]

In [18]:
smrt_dataset_df.loc[mask_duplicated, ["inchi","rt", "old_rt"]]

                                                   inchi      rt  old_rt
11     InChI=1S/C4H8N2O2/c5-3-1-2-6(8)4(3)7/h3,8H,1-2...   620.6   620.6
42     InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-...   638.0   638.0
54     InChI=1S/C17H25NO/c19-17-9-5-4-8-16(17)18-12-1...   679.1   679.1
176    InChI=1S/C26H28ClNO/c1-3-28(4-2)19-20-29-24-17...  1008.2  1008.2
615    InChI=1S/C17H21NO4/c1-18-13-7-11(8-14(18)16-15...   581.3   581.3
708    InChI=1S/C13H15NO2/c15-12-7-9-4-5-10-8-13(9,16...    86.4    86.4
1489   InChI=1S/C29H41F2N5O/c1-19(2)27-34-33-20(3)36(...   665.8   665.8
3896   InChI=1S/C16H24O4/c1-11-5-3-2-4-6-12-9-13(17)1...   781.6   781.6
3934   InChI=1S/C13H13N3/c1-2-16-13-5-11-9-3-8(6-14-7...   101.1   101.1
4147   InChI=1S/C15H20O3/c1-9-5-4-8-15(3)13(18-15)12-...   972.3   972.3
4168   InChI=1S/C21H24N2O2/c1-3-14-10-13-11-21(20(24)...   727.8   727.8
4178   InChI=1S/C26H25NO4/c28-18-8-7-15-11-20-26(29)1...   673.4   673.4
4376   InChI=1S/C27H42N2O5S/c1-15-9-8-10-27(7)22(34-2...   707.1   707.1
4887   InChI=1S/C23H27N5/c1-19-23(20(2)28(25-19)22-11...   687.2   687.2
6821   InChI=1S/C26H26N2O3/c1-14(2)13-28-10-9-25-21-1...   646.7   646.7
6843   InChI=1S/C26H26N2O3/c29-19-8-7-15-11-20-26(30)...   716.8   716.8
12892  InChI=1S/C21H27NO4/c23-14-5-4-13-10-16-21(25)7...   635.1   635.1

Let's map the mean rt values for those rows whose inchi is in the duplicated list

In [19]:
rt_map = smrt_dataset_repeated_aggregated_df.set_index("inchi")["rt_mean"]
smrt_dataset_df["rt"] = (
    smrt_dataset_df["inchi"].map(rt_map).fillna(smrt_dataset_df["old_rt"])
)

In [20]:
smrt_dataset_df.loc[mask_duplicated, ["inchi","rt", "old_rt"]]

                                                   inchi           rt  old_rt
11     InChI=1S/C4H8N2O2/c5-3-1-2-6(8)4(3)7/h3,8H,1-2...   623.700000   620.6
42     InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-...   639.466667   638.0
54     InChI=1S/C17H25NO/c19-17-9-5-4-8-16(17)18-12-1...   690.500000   679.1
176    InChI=1S/C26H28ClNO/c1-3-28(4-2)19-20-29-24-17...  1001.900000  1008.2
615    InChI=1S/C17H21NO4/c1-18-13-7-11(8-14(18)16-15...   600.350000   581.3
708    InChI=1S/C13H15NO2/c15-12-7-9-4-5-10-8-13(9,16...    90.450000    86.4
1489   InChI=1S/C29H41F2N5O/c1-19(2)27-34-33-20(3)36(...   670.150000   665.8
3896   InChI=1S/C16H24O4/c1-11-5-3-2-4-6-12-9-13(17)1...   756.900000   781.6
3934   InChI=1S/C13H13N3/c1-2-16-13-5-11-9-3-8(6-14-7...    96.700000   101.1
4147   InChI=1S/C15H20O3/c1-9-5-4-8-15(3)13(18-15)12-...   904.766667   972.3
4168   InChI=1S/C21H24N2O2/c1-3-14-10-13-11-21(20(24)...   704.450000   727.8
4178   InChI=1S/C26H25NO4/c28-18-8-7-15-11-20-26(29)1...   687.700000   673.4
4376   InChI=1S/C27H42N2O5S/c1-15-9-8-10-27(7)22(34-2...   687.450000   707.1
4887   InChI=1S/C23H27N5/c1-19-23(20(2)28(25-19)22-11...   713.300000   687.2
6821   InChI=1S/C26H26N2O3/c1-14(2)13-28-10-9-25-21-1...   675.050000   646.7
6843   InChI=1S/C26H26N2O3/c29-19-8-7-15-11-20-26(30)...   704.400000   716.8
12892  InChI=1S/C21H27NO4/c23-14-5-4-13-10-16-21(25)7...   627.000000   635.1

Drop the old rt column

In [21]:
smrt_dataset_df.drop(["old_rt"], inplace=True, axis=1)
smrt_dataset_df.head()

   pubchem     rt                                              inchi
0     5139   93.5    InChI=1S/C3H8N2S/c1-2-6-3(4)5/h2H2,1H3,(H3,4,5)
1     3505  687.8  InChI=1S/C19H25Cl2N3O3/c1-27-19(26)23-8-9-24(1...
2     2159  590.7  InChI=1S/C17H27N3O4S/c1-4-20-8-6-7-12(20)11-19...
3     1340  583.6  InChI=1S/C9H7NO2/c11-8-3-1-2-7-6(8)4-5-10-9(7)...
4     3344  579.0  InChI=1S/C15H20N2O2/c18-14-16-12-15(19-14)7-10...

## Get SMILES from InChI

In [22]:
smrt_dataset_df['SMILES'] = smrt_dataset_df["inchi"].apply(inchi_to_smiles)

[18:37:10] Explicit valence for atom # 14 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 14 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 17 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 17 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 15 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 23 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 23 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 15 N, 4, is greater than permitted

[18:37:10] Explicit valence for atom # 20 N, 4, is greater than permitted
[18:37:10] ERROR: Explicit valence for atom # 20 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 15 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 14 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 14 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 15 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 17 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 17 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 13 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 13 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 26 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 26 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 25 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 25 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 11 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 11 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 26 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 26 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:11] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:11] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 24 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 24 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 14 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 14 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 21 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 21 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 24 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 24 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 20 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 20 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 14 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 14 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 25 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 25 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 25 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 25 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 10 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 15 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 20 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 20 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:12] Explicit valence for atom # 26 N, 4, is greater than permitted
[18:37:12] ERROR: Explicit valence for atom # 26 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 27 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 27 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 13 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 13 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 23 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 23 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 17 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 17 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 24 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 24 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 22 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 22 N, 4, is greater than permitted

[18:37:13] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:13] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 17 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 17 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 17 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 17 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 22 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 22 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 20 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 20 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 21 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 21 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 15 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 22 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 22 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 24 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 24 N, 4, is greater than permitted

[18:37:14] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:14] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:15] WARNING:  Problems/mismatches: Mobile-H( Hydrogens: Locations or number; Mobile-H groups: Attachment points, Number)

[18:37:17] Explicit valence for atom # 22 N, 4, is greater than permitted
[18:37:17] ERROR: Explicit valence for atom # 22 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 25 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 25 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 21 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 21 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 21 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 21 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 23 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 23 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 22 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 22 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 22 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 22 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 22 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 22 N, 4, is greater than permitted

[18:37:18] Explicit valence for atom # 18 N, 4, is greater than permitted
[18:37:18] ERROR: Explicit valence for atom # 18 N, 4, is greater than permitted

[18:37:19] Explicit valence for atom # 24 N, 4, is greater than permitted
[18:37:19] ERROR: Explicit valence for atom # 24 N, 4, is greater than permitted

[18:37:21] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:21] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:23] Explicit valence for atom # 25 N, 4, is greater than permitted
[18:37:23] ERROR: Explicit valence for atom # 25 N, 4, is greater than permitted

[18:37:25] Explicit valence for atom # 19 N, 4, is greater than permitted
[18:37:25] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted

[18:37:25] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:25] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

[18:37:26] Explicit valence for atom # 21 N, 4, is greater than permitted
[18:37:26] ERROR: Explicit valence for atom # 21 N, 4, is greater than permitted

[18:37:39] Explicit valence for atom # 16 N, 4, is greater than permitted
[18:37:39] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted

As it was evident by the logs, not all molecules could be converted to SMILES

In [23]:
smrt_dataset_df.describe(include=['category', 'object'])

/tmp/ipykernel_49004/2913326157.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  smrt_dataset_df.describe(include=['category', 'object'])

                                                  inchi     SMILES
count                                             80019      79938
unique                                            80019      79938
top     InChI=1S/C3H8N2S/c1-2-6-3(4)5/h2H2,1H3,(H3,4,5)  CCSC(=N)N
freq                                                  1          1

Eighty-one molecules fail during the conversion, let's remove them from the dataset

In [24]:
print(smrt_dataset_df.shape)
smrt_dataset_df.dropna(axis=0, subset=['SMILES'], inplace=True)
print(smrt_dataset_df.shape)

(80019, 4)
(79938, 4)

## Save the Processed Dataset to File

In [26]:
smrt_dataset_df.to_csv(PROCESSED_SMRT_FILE, sep=";", index=False)